### ISSUE TITLE
開始時にチャットに何処のルームが開始されたかを通知して欲しい

### ISSUE THREAD

**Issue by kazu0617** [kotmw0701/Splatoon-in-Minecraft#1]
タイトルのとおりですが、他のルームで始まった時に実際に始まったのかどうかがルームに入った人にはわからないので、できればルームに入っていない人（もしくは、全員）に
「[room]でゲームが開始されました！」
「[room]でゲームが終了しました」
と言ったログが出ると入っていない人にも分かりやすいかな、と思いました。

**Comment by kotmw0701** [comment]
確かにそれは一理ありますね・・・
次バージョンでの仕様化しますね(/・ω・)/
